### ISSUE TITLE
need null checking when calling C API

### ISSUE THREAD

**Issue by Wiladams** [blend2d/blend2d#11]
Null checking might be a good idea in the C interface as it goes through obj->impl->virt->func(ctx)…

Right now it will crash.  Maybe those functions should return 'false' and a parameter error?  That will really muddy the ease of the interface, but might be necessary?  Or just allow to crash as a fail fast, where params checking can happen elsewhere.

**Comment by kobalicek** [comment]
The object must be initialized otherwise it's undefined what would happen. It's very similar like passing null FILE* pointer to `fwrite()`, for example, etc... Blend2D instances must be initialized by `Init()` before use and destroyed by `Reset()` after they go out of scope. C++ API does it by design, C API doesn't.

**Comment by Wiladams** [comment]
Yah, I figured as much.  The 'C' interface is essentially "no guard rails", which is fine as for my own LuaJIT wrapper, I'm doing what the C++ interface does (init, reset).  It might just be worthwhile documenting the fact that the C interface is more "raw".  I know it's already documented that you SHOULD do the Init/Reset thing, but maybe more explicit?

This wasn't actually a problem for me, I ran into by accident.

So far so good overall.
