### ISSUE TITLE
Drawing line cap issues when calling close after lineTo?

### ISSUE THREAD

**Issue by LostVector** [blend2d/blend2d#116]
>   BLImage img(512, 512, BL_FORMAT_PRGB32);
>   BLContext ctx(img, cci);
>   ctx.clearAll();
> 
>   // Diagonal line
>   BLPath path;
>   path.moveTo(0,0);
>   path.lineTo(256,256);
> //  path.close();
> 
>   ctx.setStrokeStyle(BLRgba32(0xFFFF8000));
>   ctx.setStrokeWidth(3);
>   ctx.setStrokeStartCap(BL_STROKE_CAP_BUTT);
>   ctx.setStrokeEndCap(BL_STROKE_CAP_BUTT);
>   ctx.strokePath(path);
> 
>   // vertical line
>   path.clear();
>   path.moveTo(256,0);
>   path.lineTo(256,512);
>   // path.close();
> 
>   ctx.strokePath(path);
>   return img;

The vertical line is just drawn for a reference point vis-a-vis the diagonal line.

So the issue I'm seeing here with the diagonal line if I uncomment the close is that the line end juts out past the center point even though the caps are explicitly of type BL_STROKE_CAP_BUTT (and it's my understanding this should be the default anyway). Should that be the case or am I missing something?

**Comment by kobalicek** [comment]
I think the problem is that the default join in Blend2D is `miter-clip`, if I set it to bevel it produces the desired output:

```
ctx.setStrokeJoin(BL_STROKE_JOIN_MITER_BEVEL);
```

Blend2D does this on purpose as usually miter-clip is what you would expect and which works well with animations. I don't think this is a bug, it's hard to verify as miter-clip is not supported by all the libs around.

**Comment by LostVector** [comment]
Yes, I think that must be it.  The miter default type I'm used to is bevel and that does fix the issue.
