### ISSUE TITLE
C++ Api: BLContext missing fillArc function

### ISSUE THREAD

**Issue by Veykril** [blend2d/blend2d#12]
While looking through the C++ API for recreating it in Rust I noticed that BLContext seems to be missing an implementation for `fillArc`, it has the chord and pie functions
https://github.com/blend2d/blend2d/blob/1087ac5ab589cd6fdfd3997fbfbb2679a0680e13/src/blend2d/blcontext.h#L1011-L1023
and it has all three, arc, pie and chord functions for strokes.
https://github.com/blend2d/blend2d/blob/1087ac5ab589cd6fdfd3997fbfbb2679a0680e13/src/blend2d/blcontext.h#L1158-L1177
So I assume this one has been forgotten?

**Comment by kobalicek** [comment]
This is correct. `fillArc` would behave the same as `fillChord` in this case. It's very similar to `strokePolyline()` vs `strokePolygon()` - there is also only `fillPolygon()` as  `fillPolyline()` would behave identically.

Ironically, if you use `fillGeometry()` it's possible to pass an arc or polyline, but that's because internally it doesn't matter as non-closed figures are always implicitly closed by edge-builder.

**Comment by Veykril** [comment]
Ah I see, thanks for the explanation!
