### ISSUE TITLE
Checking with PVS-Studio static analyser

### ISSUE THREAD

**Issue by KurenevAlexandr** [blend2d/blend2d#120]
To demonstrate the capabilities of our analyzer, we regularly perform analysis of open source projects. We had recently checked the Blend2D project.

Here is the link to the article about it (we check c484790 version): https://habr.com/ru/post/593161/
Open Source projects can use PVS-Studio as free

**Comment by kobalicek** [comment]
Thank you for doing the analysis!

I would like to comment the findings though:

1. An always-false expression `blJpegDecoderImplProcessMarker()`

  * the finding may be true, but it's not a bug. There is tons of JPEG features not supported, and this is just one of them.

2. A typo in the function's signature - `blIsCubicFlat()`

  * that's a valid issue, however, it's only cosmetic and the number in `[]` has no effect (will be fixed though).

3. An extra evaluation due to an incorrect operator - `isObject()` 

  * that's an invalid issue and assumption. In this case you really want a branchless check, the `&` is there on purpose, like in other places where `&` is used instead of `&&`.

4. A redundant check - `BLRasterWorkerManager::reset()`

  * that's an invalid issue. The `reset()` function is responsible for cleanup. It doesn't dictate how it must be initialized. It uses `_threadPool`, because you cannot allocate worker threads without thread pool, but since its purpose is to cleanup the data, it will check whether `_threadPool` is non-null before releasing it, because maybe in other branches it will have to cleanup `_threadPool` while there are no workers allocated, maybe in some future version too. I think a pedantic check that seems redundant (now) is better than a memory leak in the future, when the implementation is extended.

5. Using an uninitialized variable - `bl_convert_multi_step()`

  * that's a valid issue, which I found fixed in my dev branch :)

6. An always-true check - `blPngDeinterlaceBits()`

  * that's a valid issue, however, this is harmless. I will remove the check though.

7. A copy-paste error - `BLString::begin()`

  * that's a valid issue, which is not present in my dev branch as `BLString` was completely reimplemented.

8. Another copy-paste error - `bl_convert_argb32_from_prgb_any()`

  * that's a valid issue, which I'm gonna fix.

9. An idempotent loop - `mapTextToGlyphsFormat0()`

  * that's a valid issue.

In the end, only 5, 7, 8, and 9 were real issues, and I will close this issue when these are fixed in master branch.

I think that Blend2D needs more unit and integration tests - and running these tests with ASAN/UBSAN. These tools helped me to fix dozens of issues during the development. In my experience, what is tested has almost zero bugs, what is not tested, always has some.
