### ISSUE TITLE
Maybe image read/write could be a separate thing

### ISSUE THREAD

**Issue by Wiladams** [blend2d/blend2d#13]
I don't find image reading/writing to be an integral part of a 2D graphics library.  Maybe this could be a separate 'module'.  That way it can easily be added onto (I want Targa), without waiting on the primary library?

As long as it's there, it would be nice to be able to write the format into a memory buffer, or into a 'stream-like' interface.  In many of my scenarios, I want to stream an image across  the net for live viewing, and writing it into a file first isn't necessary.  Maybe the file writing could simply use this 'write to buffer' thing, or simply be separate (yah, not everyone wants to create a buffer just to write in a particular format).

At any rate, more of a suggestion than 'issue'.

**Comment by kobalicek** [comment]
You can completely ignore IO API if you don't want it, but believe me it's just a tiny part of the library that has some interesting optimizations not found in stock libpng, for example. Image IO makes it possible to write examples that can read resources and then write the result somewhere.

Image buffers are supported (`readFromData` and `writeToData`), but not streams. I didn't want to complicate the library with streams initially so maybe in the future, for now I wanted to keep things simple.

BTW I wrote already TGA codec, but I removed it as I wasn't sure whether it's useful. It's possible to implement your own image codecs and add them to Blend2D (this is why there is `<blend2d-impl.h>`), but I first need to document this a bit and since Blend2D offers C API it's a bit verbose to do so.

**Comment by Wiladams** [comment]
I figured as much.
When I say "stream' I don't mean the C++ variety.  Just something simple.  But, I see the writeToData, so maybe that's good enough.

I'd like to see your TGA implementation as template for doing images, then I might add a few.

LuaJIT version is shaping up nicely.
________________________________

**Comment by Wiladams** [comment]
but, I see the PNG and BMP ones, so maybe I'll just give it a try
