### ISSUE TITLE
Change interface to make possible to use library on "old" compillers without "->_d.impl" hacks

### ISSUE THREAD

**Issue by JouriM66** [blend2d/blend2d#130]
A lot of library functions can be accessed only using "internal" mecanics like casting from "_d.impl" pointers to actual implementation.
Using such code in application may be huge problem if some internals changes in future.
I think its needed to add all such functional to system headers and make them looks like functions.

F.i. to get current stroke width value now I need to use something like this:
```
BLContextCore *core;
double old_width = ((BLContextImpl*)core->_d.impl)->state->strokeOptions.width;
```
I think its much better to have something like:
```
#define blGetStrokeWidth( ctx ) ((BLContextImpl*)(ctx)->_d.impl)->state->strokeOptions.width
```
in system header for ANSI and inline function for C++ mode.

**Comment by kobalicek** [comment]
I agree that getting a stroke width is kinda complicated, because an official C API way is to go over `blContextGetStrokeOptions()` and extract it from there. However, I think this could be solved by a dedicated C API function like `blContextGetStrokeWidth()` - correct?

There is a good reason that there are no macros that would act as inline functions, because these macros are not useful when interfacing with Blend2D from non-C languages.

**Comment by kobalicek** [comment]
I think we are talking about the same. If there is a missing C API it should be added, but as C API and not as `#define`. I can review the rendering context, so far nobody complained so that's maybe why it's missing, as I have missed it :)

BTW you don't need your own blDestroy - there is `blVarDestroy()` that fits this purpose. The reason why there are destroy functions for every object type is to make it typed and to verify whether the destroyed object is of the correct type in debug builds.

**Comment by JouriM66** [comment]
Thanks for remind about blVarDestroy. I was trying to use it but has some kind of issues. But cant remember :)
Ill give it another try.

Im trying to use blend now and found some errors and lack of functionality.
F.i.:
1. blFontCreateFromFace can not be used with uninitialized font (blend traps trying to access NULL). But all other objects can, so I think its error. I fixed this.
2. Its impossible to get error code AFTER some functions calls and where is no such think like blErrorString. I changed this and "invented" error2string function.

The question is: do these changes needed and, if so, how to publish them?

**Comment by kobalicek** [comment]
This commit should add some missing C API:
  - https://github.com/blend2d/blend2d/commit/63db360c7eb2c1c3ca9cd92a867dbb23dc95ca7d

Anything else missing?

**Comment by kobalicek** [comment]
BTW `blFontCreateFromFace()` - the BLFont you call this on must be initialized before. `blSomeObjectInit...()` initializes an object, `blSomeObjectCreate()` would setup an already initialized object.

**Comment by JouriM66** [comment]
> Anything else missing?

As for me iv no idea.
Im not using pure C API, im using C++ but older in standard.
I just point out what big part of API is for C++ only.
Since we agreed what my and yours points of view on how solid library API must looks like are very different you at you own in this war :)

PS: As for me, the main problem is not mossing some API for ansi C (if nobody asks, it means nobody uses it, so why to bother?). The main problem is almost total missing of documentation. As for me Im little bit tired to reverce engeneering sources in attempts to understand what some interface do, how it works and why it works as it work.

**Comment by JouriM66** [comment]
> BTW `blFontCreateFromFace()` - the BLFont you call this on must be initialized before

Its artificial limitation your apply in blFontCreateFromFace using assert.
I change it in "my" branch, but this is just another illustration of library inconsistent. Some objects can be created on uninitialized data, some cant. The only way to figure out which is which is to get a exception in runtime.
I dont want to remember all these differences, so I changing objects behaivor to the same in all of them.

**Comment by kobalicek** [comment]
No it's not true - `blXXXInit()` must be called to initialize the object - if you use uninitialized object with non-init function it's undefined behavior. Yes, it may work sometimes, but it's not how it's supposed to be used. The assert is there to prevent such use, you should not remove it even in your private branch.
