### ISSUE TITLE
Is it possible to enable asynchronous rendering with single thread?

### ISSUE THREAD

**Issue by x10000year** [blend2d/blend2d#151]
In my scenario, enabling asynchronous rendering could improve performance as I'm drawing several images at the same time.

**Comment by kobalicek** [comment]
Yes you can do it.

In general when you use 2 threads, Blend2D would use one extra thread and the user thread (that the user is using to interact with BLContext) - if you use only one thread, that would tell Blend2D to serialize commands to be later rendered.

To control when things are rendered, `flush(BL_CONTEXT_FLUSH_SYNC)` - note that this would start using the user thread, so in order to render the stuff in another thread, execute it from another thread, something like:

```
call_async([&]{ context->flush(); });
```

Let me know whether this helps

**Comment by kobalicek** [comment]
Closing, I hope the question got answered, if not, please reopen
