### ISSUE TITLE
loss glyphSize in BLGlyphRun ?

### ISSUE THREAD

**Issue by miaotianlei** [blend2d/blend2d#165]
Why

**Comment by kobalicek** [comment]
To simplify the implementation.

There are already proposals to extend glyph ids beyond 16 bits in OpenType so a single font could cover all languages. I think it's better to support one glyph id unit than multiple ones when it comes to these, because it only made things harder to read and harder to use.

I didn't think anyone would be using 16-bit glyph ids as most text shaping libs use 32 bits anyway.

**Comment by miaotianlei** [comment]
> To simplify the implementation.
> 
> There are already proposals to extend glyph ids beyond 16 bits in OpenType so a single font could cover all languages. I think it's better to support one glyph id unit than multiple ones when it comes to these, because it only made things harder to read and harder to use (and of course harder to implement).
> 
> I didn't think anyone would be using 16-bit glyph ids as most text shaping libs use 32 bits anyway.

Will codes fill glyphSize automatically? We don't care it. In website, the example still use it.

**Comment by kobalicek** [comment]
If you were using standard `4` in `glyphSize` then this is now basically implied. Can you describe the issue that you have?

**Comment by miaotianlei** [comment]
ok, I only sure the field isn't filled. Thank you.
