### ISSUE TITLE
Is there a dirty region available?

### ISSUE THREAD

**Issue by Wiladams** [blend2d/blend2d#19]
I'd like to optimize drawing to the screen.  I think I'd like to have access to a dirty region of that's available.  Otherwise, is the general idea to simply blit the whole framebuffer as that's fast enough these days?  I did see a discussion of 30fps blits on 4k displays.

**Comment by kobalicek** [comment]
There is no dirty region in the rendering context. The idea here is that if you render to a framebuffer then you should track which areas should be updated. Modern framebuffers usually require double or triple buffering so dirty regions would probably not really help here).

I have some future plans with the rendering context that could be compatible with tracking which areas changed, but it would most probably be blocks of predefined size instead of the region, however, it would be convertible to region as well.

**Comment by Wiladams** [comment]
Sounds good.  I can track in my rendering context wrapper.  Another use case is remote viewing, where I'd like to send only changes every once in awhile.
