### ISSUE TITLE
Please, provide tags in Github

### ISSUE THREAD

**Issue by uilianries** [blend2d/blend2d#203]
Hello!

The download page offers tagged versions to be copied: https://blend2d.com/download.html

So far, only the version 0.11.1 is available.

The previous versions: 0.10.6 0.10.5 0.10.4 0.10 0.9 0.8 0.0.18 and so on are no longer available in the download page, and it's fine. However, it would be great having any tag available in Github too: https://github.com/blend2d/blend2d/tags so people could track all available version without risk of losing a version from the download page.

**Comment by kobalicek** [comment]
Yeah, losing the previous versions was unfortunately caused by my update script, which deleted them during the site-update. Sorry about that - I hope this is not going to happen again.

On the other hand, I think uses of older versions should disappear - compared to the latest release they were buggy and the older releases would not even compile with the latest asmjit, which means that you would need to tag both - blend2d and asmjit to be able to compile them - and this is something I'm not going to backtrack as there is are benefits in using the older versions.

BTW I plan to use tags, but I expected to be using them after 1.0.0 when Blend2D gets ABI stability - now the ABI stability is not guaranteed between releases. Maybe I will reconsider, but sorry I'm not going to tag previous releases for sure.

**Comment by uilianries** [comment]
@kobalicek Thank you for your quick answer!

Tags are more important in terms of being able to track the changes. In the download page we have the version 0.11.1, but is not so easy to track which commit is related to that release.

**Comment by uilianries** [comment]
> Would having the commit hash on the download page help in this case? That would be something I could add.

@kobalicek Yes, it would help a lot!

**Comment by kobalicek** [comment]
I added the commit hash to the download page so it can be tracked, is that sufficient for now?

**Comment by uilianries** [comment]
@kobalicek Yes, thank you so much! It looks really nice. :green_heart: 

![Screenshot 2024-06-08 at 19-24-07 Blend2D](https://github.com/blend2d/blend2d/assets/4870173/354abee2-46ed-45df-99e0-7801d6656bbf)

I'm closing this issue as we can track releases via commits now. :smile:

**Comment by kobalicek** [comment]
@uilianries BTW there is a new option in Blend2D CMakeLists called `BLEND2D_EXTERNAL_ASMJIT` - it's a boolean, and when it's true it tells the build system to use `find_package()` instead of a bundled AsmJit in 3rdparty directory. I added this option specifically for package managers such as vcpkg or conan so it can be used instead of patching CMakeLists.txt.

**Comment by uilianries** [comment]
@kobalicek Thank you! Yes, we noted that new option when packaging the latest version. Indeed we are using it already: https://github.com/conan-io/conan-center-index/blob/2123261bdc20dc3701921ad73ac22f24641fb52b/recipes/blend2d/all/conanfile.py#L75
