### ISSUE TITLE
VCPKG update - newest version of Blend2D

### ISSUE THREAD

**Issue by JakubMelka** [blend2d/blend2d#205]
Hello, would it be possible to update the package for VCPKG to the newest version?

**Comment by kobalicek** [comment]
Hello, not at the moment, this is the blocker:

  - https://github.com/microsoft/vcpkg/pull/39090

Since vcpkg team has some weird demands about the ports I have decided not to contribute to vcpkg anymore. Anyone who wants blend2d there has to update asmjit first and a bunch of other ports with it. And then AsmJit.

Since Conan provides both recent asmjit and blend2d I think it's the time to switch to Conan instead :)

**Comment by JakubMelka** [comment]
Hello @kobalicek, I have started pull request microsoft/vcpkg#39730 for VCPKG.

**Comment by kobalicek** [comment]
Completed, thanks @JakubMelka!
