### ISSUE TITLE
Removal of -fmerge-all-constants option

### ISSUE THREAD

**Issue by atomsymbol** [blend2d/blend2d#71]
Hello. `CMakeLists.txt` uses `-fmerge-all-constants` by default. When Blend2D is for example including standard C++ header files containing inline code this option can lead to unexpected behavior because the standard header files might not have been tested with this option enabled. In C++ it is common for external header files to contain code in case they contain templates. Unless the `-fmerge-all-constants` option has a performance benefit that can be unequivocally proved by running Blend2D benchmarks, I recommend removing this option from `CMakeLists.txt` in order to increase the stability of Blend2D in the longterm.

**Comment by kobalicek** [comment]
The `-fmerge-all-constants` is not related to performance in this case, it's used to give the C++ compiler the opportunity to make the resulting binary a bit smaller at virtually no cost. Since Blend2D has a very restricted use of C++ standard library it's perfectly fine. I've been using this option for years without any problem, so unless proven that it causes problems I would keep it.

I would like to note that this flag is private, so even if you build Blend2D statically it won't propagate to your project if you use `Blend2D::Blend2D` as a CMake target.

**Comment by atomsymbol** [comment]
Seems reasonable. But an issue is that the compiler (GCC 9.3) will not print any warning if a program is taking the addresses of multiple logical variables merged into a single physical variable:

    #include <stdio.h>
    const int a = 0, b = 0;
    int main() {
    	printf("%p %p\n", &a, &b);
    	return 0;
    }

In terms of size, adding `-fdata-sections -ffunction-sections` and `-Wl,--gc-sections` further decreases the size of the code/rodata sections in libblend2d.so by about 31/1 KB.

**Comment by kobalicek** [comment]
Thanks! I will check you these flags.
